### ISSUE TITLE
Manage sketch files for design repository when new project is created

### ISSUE THREAD

**Issue by manueldahm** [opendevstack/ods-provisioning-app#114]
Ignore Sketch Files in design repo so that only the json files are versioned and not the binary files - that would otherwise create conflicts often. This for using Kactus versioning with Git.

**Comment by clemensutschig** [comment]
@manueldahm - just set gitignore

manueldahm <notifications@github.com> schrieb am Sa., 13. Apr. 2019, 13:09:

**Comment by gerardcl** [comment]
@clemensutschig the requirement is to provision a .gitignore in the `<projectID>-design` repository with:
```
*.sketch
```
by default, so UX/UI can collaborate by only using the JSON descriptors from Kactus.
It is right that it could be added later, but it would be nice to have it by default since they work without CLI, and through GUI it is easy to add by mistake the sketch binaries.

It can be done throught the provisioning app since Bitbucket has added the feature to commit files through the [API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/src#post )

What do you think?

**Comment by clemensutschig** [comment]
@gerardcl - this is Pretty tricky because the prov App today dies not commit any code.. only rundeck does...

**Comment by gerardcl** [comment]
hi! we could add the commit case for design repo after it is created at provisioning app step, or we can add the git commands in the rundeck side. If it is better to add this at rundeck side, which should be the script: export_ocp_project_metadata.sh?

**Comment by gerardcl** [comment]
@clemensutschig shall we close this issue as it is or shall we tackle any of the aforementioned options?

**Comment by gerardcl** [comment]
within current discussions there has been stated a good idea: to provide a component/quickstarter for such purpose, so whenever a UI/UX requires to track designs changes within a repository such quickstarter can provide this repository. So, if any special feature is required we can implement that in such quickstater.
what do you think @clemensutschig @michaelsauter @tjaeschke ?
if we agree on that we can later on close this ticket and create one on the right place (ods-project-quickstarters)...

**Comment by michaelsauter** [comment]
At most this should be a quickstarter. Definitely not related to the prov-app. However, I believe the value of such a quickstarter is so minimal that it might not be worth adding one. I'll close this. Please reopen in ods-quickstarters if you really believe this is necessary.
