### ISSUE TITLE
MailConnectException/healthcheck when mail configuration is invalid even if mail is disabled in configuration

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-provisioning-app#160]
Given an invalid email configuration ( e.g. ip adress invalid):

`mail.enabled=false`
`spring.mail.host=127.0.0.2`

The application throws MailConnectException:

> 2019-06-27 10:22:50 WARN  o.s.b.a.mail.MailHealthIndicator - Mail health check failed
> com.sun.mail.util.MailConnectException: Couldn't connect to host, port: 127.0.0.2, 25; timeout -1
>	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209)

The health check should not be executed, because mail is disabled in configuration.

**Comment by clemensutschig** [comment]
@stefanlack  - can you provide the full stack? it#s really weird, because - the check is way before any email magic..

https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/MailAdapter.java#L66

maybe the spring init .. does some magic here?

**Comment by stefanlack** [comment]
Just adding `management.health.mail.enabled=false` to the properties disable mail health check.

**Comment by clemensutschig** [comment]
top!

**Comment by stefanlack** [comment]
I will just add `management.health.mail.enabled=${mail.enabled}` to application.properties.

**Comment by stitakis** [comment]
@stefanlack please add me as reviewer once you are done with change
