### ISSUE TITLE
Verify keycloak Setup documentation

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#223]
@stefanlack - can ypu Please ensure the antorra doc is really up2date. 1.2 introduced this major Change..  and we need to ensure People can install/ configure this.

**Comment by stefanlack** [comment]
@clemensutschig :
- regarding provisioning app itself, a updated documentation was created and is available at https://www.opendevstack.org/ods-documentation/ods-provisioning-app/latest/index.html#_authentication_configuration 

Is there anything we missed here in the documentation regarding provisioning app?

Notes:
- While we only tested our implementation with keycloak, it is not bound to keycloak. Every OAUTH2 -/ Openid implementation server should.
- Documentation of using keycloak instead of crowd  is missing in the gettig started guide. I have created the issue at https://github.com/opendevstack/ods-core/issues/182

**Comment by stefanlack** [comment]
@clemensutschig is this ticket still needed? If yes: Can you please answer my questions, so that I can help you? Otherwise please close this issue. Thanks!

**Comment by stefanlack** [comment]
@clemensutschig : ping.

**Comment by stefanlack** [comment]
closed, because we did not got feedback. 
@clemensutschig please feel free to reopen ticket and specify further details.
