### ISSUE TITLE
Be able to only provision bitbucket project without OpenShift project

### ISSUE THREAD

**Issue by segator** [opendevstack/ods-provisioning-app#434]
We need prov-app is able to deploy jira, confluence and bitbucket but no openshift project + ODS project.

Right now there is a flag "platform project" when selected it creates bitbucket +openshift project,
it will be nice if we can split this in 2 flags.

**Comment by stitakis** [comment]
@michaelsauter @segator 
This is the proposal:
- to add a the new flag `bitbucketProject = true/false` 
- Detail: if `platformRuntime` is `true` and new flag `bitbucketProject` is also `true` then `platformRuntime` will be created. (Note: It might sound obvoius but we need to deal with this in situation in the code)

**Comment by stitakis** [comment]
@michaelsauter @clemensutschig @segator due lack of time I'll not able to finish it in ODS 3.x, I'll move it to ODS 4.x, agree?

**Comment by michaelsauter** [comment]
Fine by me.

**Comment by metmajer** [comment]
Let’s pick it up when you’re back and we shoot for releasing with ODS 3.1 in September @martsec

**Comment by martsec** [comment]
@segator  Here we would like to provision the atlassian stack without openshift, right? Full JIra/confluence and bb

FGYI @stitakis

**Comment by segator** [comment]
HI I would like to be able to decide wich components to deploy.
We have cases that we need only BB, others only jira.
So something like this is what will help us.
- [ ] Bitbucket
- [ ] Confluence
- [ ] Jira
- [ ] Openshift/ODS

**Comment by metmajer** [comment]
@martsec @segator @stitakis I assume we're talking about a REST endpoint here, correct?

**Comment by stitakis** [comment]
@metmajer we will limit this change to the REST endpoint for ODS 3.1.0 release. But to double check, what is the background of your question?

**Comment by stitakis** [comment]
@metmajer I'm descoping this issue from ODS 3.1. I'll not be able to implement it before release date in october.

**Comment by stitakis** [comment]
@segator as discussed yesterday...
4 flags will need to be available in the project provisiong API:
- openshift + bitbucket (because creation of openshift project without bitbucket is not supported)
- bitbucket
- jira
- confluence

Backwarks compatibility for current flags
- this needs to be reviewed, eventually not supported

UI
- the flags mentioned above need to be added to the current UI.

**Comment by clemensutschig** [comment]
Why are we doing this? - if it#s purely bitbucket - no ODS - it's 5 mins of
work by hand .. does that warrant the investment?

**Comment by stitakis** [comment]
well I guess this depends on the number of times that you need to do it by hand... but I don't have an overview about how often is this required and/or impact in current daily business of this missing feature... @segator is this urgent or we should reconsider/plan/include in next release?

**Comment by segator** [comment]
We have usecase people dont need openshift, but bitbucket, right now they
are consuming a lot of resources on openshift because we can not create the
project without ods project, so to avoid this waste of resources we need to
split the flag on 2.

**Comment by metmajer** [comment]
@segator @stitakis thanks for taking this further. I would like to better understand the following questions before we move along with a solution:

1) What does your approach mean for us / the end-user if it is later decided to use OpenShift as part of their project?
2) Is the provisioning app really the best way to create a pure Atlassian Stack project?
3) What about creating the OpenShift project, but disable the resources in the project (Jenkins)? Don't think that there are other resources that consume resources in an otherwise idle project?

**Comment by metmajer** [comment]
@segator let's focus on an automated scale-to-0 approach for the EDP, which is the more sustainable approach. I am closing this issue in favor of the other approach, thanks!

**Comment by stitakis** [comment]
@metmajer sounds good for me... I have added the tag `invalid` to differentiate this issue from the issues that provide changes to the code.
