### ISSUE TITLE
Jira user preflight check needs to be configurable

### ISSUE THREAD

**Issue by oalyman** [opendevstack/ods-provisioning-app#436]
**Is your feature request related to a problem? Please describe.**
The Jira preflight check for a user compares the username in the prov-app with the `key` attribute from the result of calling Jira API Get user (https://docs.atlassian.com/software/jira/docs/api/REST/8.8.1/#api/2/user-getUser)

As the example payload of the link above already shows the `key` attribute might not be what you expect as a username.

For some installation the username is the email address and thus it would make more sense to compare against the `emailAddress` attribute.

**Describe the solution you'd like**
IMO the attribute to compare against should be configurable, or maybe even a json path expression...

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by stitakis** [comment]
@oalyman thanks for reporting and investigating this... I'll take a look asap

**Comment by stitakis** [comment]
@oalyman I have analysed this a bit...

currently the ProvApp uses the api `rest/api/latest/user?username=<USERNAME>` to check if a user exists in Jira, where `USERNAME` is `key` in json response.

This logic works fine for technical account and for real users mostly all the time.

If we make it configurable to either check `key` or `emailAddress`:
- will fix the problem with users having a different `username` than `emailAddress`
- but for technical account will fail because the username of technical account mostly do not match the email address (e.g. it could be an administrators distribution list, a real user email address, etc...)

I have a solution: ProvApp check boths. First `key` and fallback to `emailAddress` if first check fails.
```
return containsUser(json, `key`, username) || containsUser(json, `email`, username)
```

What do you think?
