### ISSUE TITLE
numbers in project name causes project provision to fail

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#495]
This is a regression issue not captured by unit test.
Since #494 project provision fails because the name is validated as invalid due to numbers in the name.

**Comment by stitakis** [comment]
@michaelsauter to confirm, we want to support numbers in component names, right? Numbers in between or at end of component should be allowed but not at beginning, right?

**Comment by michaelsauter** [comment]
Sorry, are we talking project or component names? I am not sure now which one you are referring to.

For component names: from what I understand, e.g. Angular does not like numbers at the end in names. I'm ok with just preventing this problem, but I think regexes are hard to communicate and often cause more problems. Which is why I think just preventing all numbers is not a bad idea either.

For project names, I don't think we should / need to prevent numbers - they project key is anyway suffixed with -dev, -test, -cd.

**Comment by stitakis** [comment]
@michaelsauter my bad... I'm referring to project names (not component names). I'll fix by allowing numbers to be included in the project name.
