### ISSUE TITLE
Allow digits in Component names

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/ods-provisioning-app#625]
I would like to be able to use digits in component names:

A regex that would accomplish this is:

```
^(([A-Za-z][-a-zA-Z0-9]*)?[A-Za-z][0-9]?)?$
```

![image](https://user-images.githubusercontent.com/36151/97334430-08a5e300-187d-11eb-890d-baa1265caf9a.png)

https://github.com/opendevstack/ods-provisioning-app/blob/13f626ce59f48bc090ef7c234322d249700225eb/src/main/java/org/opendevstack/provision/model/OpenProjectDataValidator.java#L36

**Comment by michaelsauter** [comment]
This is because of https://github.com/opendevstack/ods-provisioning-app/issues/175.

A potential solution has been discussed before at https://github.com/opendevstack/ods-provisioning-app/pull/234.

It's not as easy as it seems at first glance, and unless there is a simple improvement that fits all quickstarters, personally I'm not convinced the complexity is worth the benefit.

**Comment by serverhorror** [comment]
Wait... so because one single framework has trouble all others prohibited too?

Being pedantic I could argue that valid angular project names are disallowed too:

* `fe-angular-proj7`, `my-component-v3` would be valid
* `7fe-angular-proj`, `fe-7angular-proj` would be invalid (IIUC angular doesn't like numbers at the beginning of a "segment" or "number only" segments)

**Comment by michaelsauter** [comment]
> Wait... so because one single framework has trouble all others prohibited too?

Correct. If you have an easy suggestion to fix the problem, or even better an implementation, happy to merge it in.

**Comment by stitakis** [comment]
@serverhorror I'm closing this item... please let me know if we should reopen it.
