### ISSUE TITLE
Allow custom quickstarters

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/ods-provisioning-app#649]
**Is your feature request related to a problem? Please describe.**

We are using a lot of different components and have to apply the same changes to all of them. It would great to use our own quickstarters without having to submit them to the project.

They hold organization internal information or are very specific to a group.

**Describe the solution you'd like**

I would like to be able to point the provisioning to a git repository that has the code for our quickstarter

**Describe alternatives you've considered**

* Submitting code upstream -- not quite applicable because
  1. we have confidential information in the quickstarters
  1. we have to wait for new releases of ODS to be made available to us

* Creating a Jenkins Shared Library -- not quite applicable because
  1. We still need to load the library in every single pipeline and there modify it

* Alternatives to rejected upstream contributions  

  Even if we decide to contribute upstream we need a way to ensure that our quickstarters are available. If they are rejected, and there might be good reasons for that, "we" still need the quickstarters to be able to use them.

**Additional context**

The quickstarters should be able to pull from password protected git repositories as well as public repositories. It _might_ make sense to restrict quickstarters to pull from a restricted set of ODS projects.

Our situation is that we use ODS projects as "management bubbles". We have accumulated 15 - 20 projects in a short amount of time because we need to restrict access between groups of people where they must not be able to see other projects or have access to the code.

**Comment by renedupont** [comment]
I looked a bit through the code and AFAIK this is already _technically_ possible. The quickstarter options that are shown in the prov-app are retrieved from a properties file like in this example: https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/resources/application-odsbox_quickstarters.properties
As you can see there, an entry for the repo exists: `jenkinspipeline.quickstarter.be-java-springboot.repo=ods-quickstarters`

To use this though, you would need to have:
- Access to the configured ods bitbucket project, because the mentioned repo property is not a full git url, it is just the repo name. Apparently the prov app adds the rest of the url from the ´bitbucket.opendevstack.project´ property, see here https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java#L198. You would need to create a repo e.g. ´custom-quickstarters´ in that ods bitbucket project and put your quickstarters in there.
- Access to this properties file which resides in the config map of the openshift ods namespace (to add entries for the prov-app, e.g. `jenkinspipeline.quickstarter.be-your-custom-component.repo=custom-quickstarters`).

Downside would be that every other user of the prov app can also provision your custom components because there is no access mgmt in place for the quickstarter themselves.

We are doing it currently this way and it works, but we have control over ODS on our cluster. I guess that won't help you since you don't have that access and your feature request is slightly different, but I just wanted to point out the current status of it.

**Comment by serverhorror** [comment]
Hi,

Sadly I don't have access to either of those.

But it is nice to have this "prepared". So there's hope after all :)

**Comment by stitakis** [comment]
@serverhorror @renedupont I propose we discuss the requirements first and agree on what would make sense to implement. I have something in my mind but I think we need to clarify a bit more, so we could shape a solution that fits ODS architecture and requirements of corporate environment.

So, first of all I'd like to clarify this:
> I would like to be able to point the provisioning to a git repository that has the code for our quickstarter

From corporate point of view (and also security and traceability point of view), I don't think it would be allowed to point the provisioning app to a public git repo (e.g. github.com, etc...). Pulling code directly from a totally unknown source and run it doesn't sound to me the correct way. Note: I define here a "public git repo"  as an unknown source of code that is not trusted by ODS.

However, if the quickstarter code is hosted in the git repository where ODS is hosted, in this case a known and trusted git repo, then I think, the provisioning app should be allowed be point to a quickstarter code. Benefits are that user and roles management and traceability are in place.

@serverhorror would be the second option ok for you?

**Comment by michaelsauter** [comment]
I would be very hesitant to add explicit support for this to ODS.

That said, quickstarter provisioning is simple, it's just creating+running a Jenkins pipeline (which ODS already abstracts so one only has to make an HTTP call to the webhook proxy). https://github.com/BIX-Digital/ods-contrib/tree/master/quickstart-with-jenkins uses this functionality in a script already. Just copy/amend this script, and point to your own repo ...

**Comment by stitakis** [comment]
> I would be very hesitant to add explicit support for this to ODS.
@michaelsauter can you please enlight us and share with us why?

**Comment by stitakis** [comment]
> That said, quickstarter provisioning is simple, it's just creating+running a Jenkins pipeline (which ODS already abstracts so one only has to make an HTTP call to the webhook proxy). https://github.com/BIX-Digital/ods-contrib/tree/master/quickstart-with-jenkins uses this functionality in a script already. Just copy/amend this script, and point to your own repo ...
@serverhorror can you please check this out again and give us feedback if this approach is good enough for you?

**Comment by michaelsauter** [comment]
Sorry yes, my reasoning:

* I believe this to be a rare use case, so I feel the effort (implementation + maintenance) is higher than the benefit
* There is a solution which I think already works pretty much as expected

If many people have a need for this feature, and the existing solution does not work for them, happy to be convinced otherwise (but then still someone would need to implement it).

**Comment by renedupont** [comment]
Maybe if @serverhorror is able to use the linked quickstart-with-jenkins script successfully for his use-case, we could request to add it to upstream for a) the use-case described in this issue here, and b) to test quickstarters locally (without using provisioning-app)?

@michaelsauter is anything speaking against that in your opinion?

**Comment by serverhorror** [comment]
I'll give the script a try. 

I've made this suggestion because I can totally se us creating a parametrized job that takes a git URL and uses whatever git repo is thrown at it. 

I'd rather see that, properly implemented, in ODS because I'm pretty sure we won't be thinking of checking whether the git clone of the quick starter is from GitHub or an "approved" endpoint. 

What's happening right now is that everyone uses the docker plain repo and replaces the content as soon as possible with whatever "template" makes sense (nope those templates are not quick starters)

I'll report back on the progress of this.

**Comment by metmajer** [comment]
As @serverhorror and I already spoke, we are working on an internal solution to allow valuable Quickstarters, provided by IT experts, to be consumed by others. However, I do not support the idea of allowing any type of Quickstarter to be offered, since this will only lead to a heap of half-baked solutions nobody will support in the end.

@serverhorror I suggest to close down this ticket.

**Comment by serverhorror** [comment]
I don't know why everyone hears "unrestricted". Allowing custom quickstarters can have restricitons in place, of course. 

@metmajer Just for my clarification, I'm trying hard to use and phrase things so they don't apply to only internal solutions. And therefore I'm trying to be less specific than I usually would be as to (1) not expose too much information, (2) not anchor people to a specific way to implement things. -- I'm not sure, am I doing this wrong?

I'll close this, no worries.

**Comment by metmajer** [comment]
@serverhorror I understand the challenge, and am facing a similar one from time to time. I believe that custom quickstarters are a better fit in our enterprise environment and should be solved outside of the provisioning app. We talked already about the opportunities, but feel free to reach out anytime!
